os: linux

matrix:
  include:
    - language: c++
      env:
        - ROOT=$PWD
      script:
        - cd common
        - mkdir -p build
        - cd build
        - cmake -DWITH_TEST_CASE=1 -DCMAKE_BUILD_TYPE=Release .. 
        - make 
        - ./test/unittest
        
    - language: php
      php: "7.4"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests/

    - language: php
      php: "7.3"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests/
    - language: php
      php: "7.2"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests/

    - language: php
      php: "7.1"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests/

    - language: php
      php: "7.0"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests/

    - language: php
      php: "5.6"
      env:
        - ROOT=$PWD
      script:
        - phpize
        - ./configure
        - make
        - make test TESTS=src/PHP/tests5/    


    - language: python
      python: "3.8"
      env:
        - ROOT=$PWD
      script:
        - cmake --version
        - pip install -r requirements.txt 
        - python setup.py install
        - nosetests src/PY/test

    - language: python
      python: "3.6"
      env:
        - ROOT=$PWD
      script:
        - cmake --version
        - pip install -r requirements.txt 
        - python setup.py install
        - nosetests src/PY/test
        
    - language: python
      python: "3.5"
      env:
        - ROOT=$PWD
      script:
        - cmake --version
        - pip install -r requirements.txt 
        - python setup.py install
        - nosetests src/PY/test

    - language: python
      python: "3.7"
      env:
        - ROOT=$PWD
      script:
        - cmake --version
        - pip install -r requirements.txt 
        - python setup.py install
        - nosetests src/PY/test

    - language: python
      python: "2.7"
      env:
        - ROOT=$PWD
      script:
        - cmake --version
        - pip install -r requirements.txt 
        - python setup.py install
        - nosetests src/PY/test --ignore-files="TestCoroutines.*"


    - language: python
      python: "3.7"
      env:
        - ROOT=$PWD
      script:
        - cd collector-agent
        - pip install -r requirements.txt
        - sh init_python_env.sh
        - nosetests Test/

notifications:
  email:
    eeliu2009@gmail.com